"use client";

import { useState } from "react";
import { ProjectState } from "@/components/project-state";
import { ProjectHeader } from "@/components/project-header";
import { ProjectNav } from "@/components/project-nav";
import { useStudio } from "@/components/studio-provider";
import { useWallet } from "@/components/wallet-provider";
import { WriteGate } from "@/components/write-gate";
import { TransactionRail } from "@/components/transaction-rail";
import { DATA_MODE } from "@/lib/genlayer/config";
import { verifiedWrite, type WriteUpdate } from "@/lib/genlayer/contract";

export default function FinalizePage(){
 const studio=useStudio(); const wallet=useWallet(); const [releaseUrl,setReleaseUrl]=useState(""); const [releaseDigest,setReleaseDigest]=useState(""); const [tx,setTx]=useState<WriteUpdate|null>(null); const [error,setError]=useState<string|null>(null);
 return <ProjectState>{({projectId,project})=>{const finalization=studio.data?.finalizations[projectId]??null;const split=studio.data?.splits[projectId];let bands:{wallet:string;dimension:string;band:number;relation:string}[]=[];try{bands=finalization?.band_matrix_json?JSON.parse(finalization.band_matrix_json):[]}catch{}
 async function request(e:React.FormEvent){e.preventDefault();if(!wallet.address)return;try{setError(null);await verifiedWrite(wallet.address,"request_finalization",[projectId,releaseUrl,releaseDigest],setTx);await studio.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Finalization request failed.")}}
 async function adjudicate(){if(!wallet.address||!project?.active_finalization_id)return;try{setError(null);await verifiedWrite(wallet.address,"adjudicate_finalization",[project.active_finalization_id],setTx);await studio.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Consensus finalization failed.")}}
 return <div className="page-wrap"><ProjectHeader project={project!}/><ProjectNav projectId={projectId}/><section className="final-desk"><div className="band-board"><p className="eyebrow">BAND MATRIX</p><h2>Validator bands</h2>{bands.length?<table><thead><tr><th>Contributor</th><th>Dimension</th><th>Band</th><th>Relation</th></tr></thead><tbody>{bands.map((b,i)=><tr key={`${b.wallet}-${b.dimension}-${i}`}><td><code>{b.wallet.slice(0,8)}…</code></td><td>{b.dimension}</td><td><strong>{b.band}</strong>/5</td><td>{b.relation}</td></tr>)}</tbody></table>:<p className="desk-empty">No accepted band matrix yet. Models never author percentages here.</p>}</div><div className="normalization-board"><p className="eyebrow">DETERMINISTIC NORMALIZATION</p><h2>Band × rubric weight → score → 10,000 bps</h2><ol><li>Consensus returns only fixed 0–5 bands.</li><li>Contract validates the complete collaborator × dimension matrix.</li><li>Integer rubric weights generate score units.</li><li>Largest-remainder allocation fixes the total at exactly 10,000.</li></ol><div className="tenk-meter"><span style={{width:`${split?.total_bps===10000?100:0}%`}}/><strong>{split?.total_bps??0} / 10,000 bps</strong></div></div><div className="split-sheet"><div className="paper-pin"/><p className="eyebrow">SPLIT SHEET</p><h2>{project!.name}</h2>{split?.entries?.length?split.entries.map(entry=><div className="split-line" key={entry.wallet}><code>{entry.wallet.slice(0,8)}…{entry.wallet.slice(-4)}</code><strong>{entry.bps} bps</strong></div>):<p>Not finalized.</p>}<div className="split-total"><span>TOTAL</span><strong>{split?.total_bps??0} bps</strong></div></div></section>
 {project!.status==="OPEN"||project!.status==="CHECKPOINTING"?<section className="session-sheet compact-sheet"><h2>Freeze release & request finalization</h2><WriteGate><form className="inline-form stack-mobile" onSubmit={request}><label>Public release URL<input type="url" value={releaseUrl} onChange={e=>setReleaseUrl(e.target.value)} required/></label><label>Release SHA-256<input className="mono" value={releaseDigest} onChange={e=>setReleaseDigest(e.target.value)} required/></label><button disabled={DATA_MODE!=="live"}>Request finalization</button></form></WriteGate></section>:null}
 {project!.status==="FINALIZATION_REQUESTED"?<section className="session-sheet compact-sheet"><h2>Run permissionless consensus</h2><p>Inputs are frozen. Any wallet may trigger the bounded validator review; state changes only after deterministic post-consensus validation.</p><WriteGate><button className="record-button" onClick={()=>void adjudicate()} disabled={DATA_MODE!=="live"}>Run adjudication</button></WriteGate></section>:null}
 {DATA_MODE!=="live"?<p className="fixture-callout standalone">Fixture mode: final split shown above is illustrative and not StudioNet proof.</p>:null}{error?<p className="inline-error">{error}</p>:null}<TransactionRail update={tx}/></div>}}</ProjectState>
}
